name: Run Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"  # same as node-cron
  workflow_dispatch:      # allows manual trigger

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run job
        run: node src/github-cron.js
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_TOKEN_HEADER: ${{ secrets.API_TOKEN_HEADER }}
          APPOINTMENTS_API_URL: ${{ secrets.APPOINTMENTS_API_URL }}
          BOOK_APPOINTMENT_ON_AVAILABLE: ${{ secrets.BOOK_APPOINTMENT_ON_AVAILABLE }}
